version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # checkout the repository
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync . s3://eoin--coders-meetup-uk--public/ --exclude '.circleci/*' --exclude '.git/*'